core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path(r'', views.index_view, name='index'),
    path(r'search/', views.search_view, name='search'),
    path(r'search/results/<int:pk>', views.detail_view, name='detail')
]

powerful_se/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex


class Post(models.Model):
    blog_name = models.CharField(max_length=120)
    post_url = models.URLField()
    post_title = models.CharField(max_length=120)
    post_subtitle = models.TextField()
    post_text = models.TextField()
    vector_column = SearchVectorField(null=True)

    class Meta:
        indexes = (GinIndex(fields=['vector_column']),)

core/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.postgres.search import SearchQuery, SearchRank, TrigramSimilarity
from django.db.models import F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . import models as m


def return_numbers_for_paginator(num_pages, page):
    """"
    A function that gives the 5 numbers to be showed in search paginator
    """
    values = [n + 1 for n in range(num_pages)][:5]
    return values if page in values else [n + page - 5 for n in values]


def index_view(request):
    return render(request, 'core/index.html')


def search_view(request):
    posts = m.Post.objects.all()
    query = request.GET.get('q')
    page_num = request.GET.get('page')

    if query is None:
        return HttpResponseRedirect(reverse('core:index'))

    search_query = SearchQuery(query, config='english')

    paginator = Paginator(
        posts.annotate(
            rank=SearchRank(F('vector_column'), search_query) + TrigramSimilarity('post_title', query)
        ).filter(rank__gte=0.15).order_by('-rank'), 15
    )

    num_results = paginator.count
    num_pages = paginator.num_pages

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        page_num = 1
        posts = paginator.page(page_num)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    # Numbers for paginator
    num_paginator = return_numbers_for_paginator(num_pages, int(page_num))

    context = {
        'posts': posts,
        'num_results': num_results,
        'num_pages': num_pages,
        'num_paginator': num_paginator,
        'first_num_paginator': num_paginator[0],
        'last_num_paginator': num_paginator[-1]
    }

    return render(request, 'core/search.html', context)


def detail_view(request, pk):
    return render(request, 'core/detail.html', {'pk': pk})

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <title>Powerful Search Engine</title>
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    {% block exclusive-styles %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
</body>
</html>

core/templates/core/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail: {{ pk }}</title>
</head>
<body>
<h1>{{ pk }}</h1>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block exclusive-styles %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <style type="text/css" data-asas-style="">
        body, div, a, p, span{ user-select: text !important; }
        p, h1, h2, h3, h4, h5, h6{ cursor: auto; user-select: text !important; }
        ::selection{ background-color: #338FFF !important; color: #fff !important; }
    </style>
{% endblock %}
{% block content %}
<div class="main-container text-center">
<main class="form-search">
    <form method="get" action="{% url 'core:search' %}?q={{ request.GET.q }}">
        <img class="mb-4" src="{% static 'images/logo.svg' %}" alt="Powerful search fake logo" width="72">
        <h1 class="h4 mb-3 fw-normal">Powerful Search Engine</h1>

        <div class="form-floating mb-3">
            <input type="search" class="form-control" id="floatingInput" name="q" value="{{ request.GET.q }}">
            <label for="floatingInput">Type your search</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Pesquisar</button>
    </form>
    <p class="mt-5 mb-3 text-muted">&copy; 2021–2021</p>
</main>
</div>
{% endblock %}

core/templates/core/search.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <aside class="searchbar">
        <div class="container mt-5 mb-5">
            <div class="d-flex flex-wrap flex-column flex-md-row
            align-items-center justify-content-center justify-content-md-start">
                <div class="mb-2 mb-md-0 me-md-2" >
                    <a href="{% url 'core:index' %}">
                        <img src="{% static 'images/logo.svg' %}" width="40">
                    </a>
                </div>
                <form class="flex-grow-1 mb-2 mb-md-0 me-md-2" method="get" action="{% url 'core:search' %}"
                      class="mb-2 mb-md-0 me-md-2">
                    <input class="form-control w-100" type="search" placeholder="Search"
                           class="" id="floatingInput" name="q" value="{{ request.GET.q }}">
                </form>
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </aside>
    <hr>
    <main class="container">
        {% if num_results > 0 %}
            <p class="text-secondary">We have {{ num_results }} result{{ num_results | pluralize }} for you</p>
            <ul class="links-list">
                {% for post in posts %}
                    <li class="links-item mb-4">
                        <div class="links-url">{{ post.post_url }}</div>
                        <a href="{% url 'core:detail' post.id %}">{{ post.post_title }}</a>
                        <p class="text-secondary">{{ post.post_subtitle | truncatewords:40 }}</p>
                        <p class="text-secondary">{{ post.post_text | truncatewords:40 }}</p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="text-center">
                <img class="m-auto" src="{% static 'images/sad_robot.png' %}" alt="A sad robot">
                <h3>We didn't find anything on our database. We're sorry.</h3>
            </div>
        {% endif %}
        <nav aria-label="Search Pagination">
            <p class="text-secondary">Page {{ request.GET.page }} of {{ num_pages }}</p>
            {% if posts.has_other_pages %}
            <ul class="pagination justify-content-start">
                {# Previous button #}
                <li class="page-item{% if not posts.has_previous %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'core:search' %}?page={% if posts.has_previous %}{{ posts.previous_page_number }}{% else %}1{% endif %}&q={{ request.GET.q }}" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {# Ellipsis button before numbers #}
                {% if first_num_paginator != 1 %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'core:search' %}?page=1&q={{ request.GET.q }}">
                         1
                    </a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        ...
                    </a>
                </li>
                {% endif %}
                {# Page number buttons #}
                {% for number in num_paginator %}
                <li class="page-item{% if posts.number == number %} active{% endif %}">
                    <a class="page-link" href="{% url 'core:search' %}?page={{ number }}&q={{ request.GET.q }}">
                        {{ number }}
                    </a>
                </li>
                {% endfor %}
                {# Ellipsis button after numbers #}
                {% if last_num_paginator != num_pages %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            ...
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{% url 'core:search' %}?page={{ num_pages }}&q={{ request.GET.q }}">
                            {{ num_pages }}
                        </a>
                    </li>
                {% endif %}
                {# Next button #}
                <li class="page-item{% if not posts.has_next  %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'core:search' %}?page={% if posts.has_next %}{{ posts.next_page_number }}{% else %}{{ num_pages }}{% endif %}&q={{ request.GET.q }}">Next</a>
                </li>
            </ul>
            {% endif %}
        </nav>
    </main>
{% endblock %}

core/templates/core/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Results: {{ search_terms }}</title>
</head>
<body>
    <h1>{{ search_terms }}</h1>
</body>
</html>